(function(){'use strict';
var KEY='lumenveil-state-v1', DEFAULT={gems:16000,pulls:0,pity5:0,pity4:0,guaranteed:false,fiveTotal:0,history:[]};
var state=load(),busy=false;
function load(){try{return Object.assign({},DEFAULT,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return Object.assign({},DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function $(id){return document.getElementById(id)}
function esc(x){return String(x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function time(x){return new Date(x).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'})}
function toast(msg){var e=document.createElement('div');e.className='toast';e.textContent=msg;$('toastRack').appendChild(e);setTimeout(function(){e.remove()},3500)}
function render(){
 $('gemCount').textContent=state.gems.toLocaleString('id-ID'); $('pity5Num').innerHTML=state.pity5+'<small>/90</small>'; $('pity4Num').innerHTML=state.pity4+'<small>/10</small>';
 $('pity5Bar').style.width=Math.min(100,state.pity5/90*100)+'%'; $('pity4Bar').style.width=Math.min(100,state.pity4/10*100)+'%'; $('guaranteeLabel').textContent=state.guaranteed?'Guaranteed ★5':'Fair 50/50';
 $('statGrid').innerHTML='<div class="stat"><b>'+state.pulls+'</b><span>Total pull</span></div><div class="stat"><b>'+state.fiveTotal+'</b><span>Legendary</span></div><div class="stat"><b>'+state.pity5+'</b><span>Jarak ★5</span></div><div class="stat"><b>'+state.history.filter(function(x){return x.rarity===4}).length+'</b><span>Rare didapat</span></div>';
 $('historyLog').innerHTML=state.history.length?state.history.slice().reverse().map(function(x){return '<div class="history-row"><b>'+('★'.repeat(x.rarity))+'</b><div><div class="item">'+esc(x.name)+'</div><time>'+time(x.time)+'</time></div><span style="color:'+x.color+'">★'+x.rarity+'</span></div>'}).join(''):'<p style="color:var(--muted)">Belum ada wish. Takdir menunggu.</p>'; save();
}
function rates(){var p=$('sidePanel'),open=p.hidden;p.hidden=!open;$('btnRates').setAttribute('aria-expanded',open);if(open)$('rateBody').innerHTML='<div class="rate-row"><span>★5 Legendary</span><b>0.6%</b></div><div class="rate-row"><span>★4 Rare</span><b>5.1%</b></div><div class="rate-row"><span>★3 Common</span><b>94.3%</b></div><p><b>Soft pity:</b> mulai pull ke-74. <b>Hard pity:</b> ★5 dijamin pull ke-90.</p><p><b>4★ guarantee:</b> maksimal 10 pull tanpa ★4. Saat ★5 muncul, 50% featured; kalah akan membuat ★5 berikutnya guaranteed.</p>'}
function results(list){var l=$('resultLayer');l.innerHTML='<h2 class="result-title">Resonansi Terbuka</h2><div class="result-grid">'+list.map(function(x,i){return '<article class="result-card" style="--rarity:'+x.color+';--delay:'+(i*100)+'ms"><div class="result-art" style="background-image:url(\''+x.image+'\')">'+x.icon+'</div><div class="result-rarity">'+(x.rarity===5?'LEGENDARY':x.rarity===4?'RARE':'COMMON')+' · ★'+x.rarity+'</div><div class="result-name">'+esc(x.name)+'</div><small>'+esc(x.title)+(x.featured?' · RATE-UP':'')+'</small></article>'}).join('')+'</div><button class="result-close" id="btnCloseResults">Kembali ke banner</button>';l.hidden=false;$('btnCloseResults').onclick=closeStage}
function closeStage(){$('stage').hidden=true;$('resultLayer').hidden=true;busy=false;render()}
function pull(n){if(busy)return;SFX.click();var cost=n===10?1600:160;if(state.gems<cost){toast('Gems tidak cukup — klik saldo untuk top-up demo.');return}busy=true;state.gems-=cost;var list=GachaCore.pull(state,n);list.forEach(function(x){state.history.push({name:x.name,rarity:x.rarity,color:x.color,time:Date.now()})});render();$('stage').hidden=false;$('btnSkip').hidden=false;$('btnSkip').onclick=function(){results(list)};Scene3D.run($('stage'),list,function(){results(list)})}
function init(){if(window.__lumenveilBooted)return;window.__lumenveilBooted=true;$('sidePanel').hidden=true;$('btnRates').onclick=rates;$('btnCloseRates').onclick=rates;$('btnPull1').onclick=function(){pull(1)};$('btnPull10').onclick=function(){pull(10)};$('btnSfx').onclick=function(){SFX.setEnabled(!SFX.isEnabled());this.setAttribute('aria-pressed',SFX.isEnabled());this.textContent=SFX.isEnabled()?'🔊 SFX':'🔇 SFX'};$('wallet').onclick=function(){state.gems+=1600;render();toast('+1,600 Gems demo ditambahkan.')};$('btnClearLog').onclick=function(){if(confirm('Hapus riwayat pull?')){state.history=[];render()}};$('btnResetAll').onclick=function(){if(confirm('Reset semua data dan pity?')){state=Object.assign({},DEFAULT);render()}};$('btnExport').onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='lumenveil-history.json';a.click()};render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
